name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%23b870ff&color_dots=%23ebedf0,%23d4a3ff,%23c48cff,%23b870ff,%237a44d8
            dist/github-snake-dark.svg?color_snake=%23b870ff&color_dots=%230d1117,%233a2359,%237a44d8,%23995cff,%23b870ff&color_background=%230d1117

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}